In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('ML Lab 3/canada_per_capita_income.csv')
df.head()

year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [3]:
df.insert(0, "bias", 1)
df.head()

bias  year  per capita income (US$)
0     1  1970              3399.299037
1     1  1971              3768.297935
2     1  1972              4251.175484
3     1  1973              4804.463248
4     1  1974              5576.514583

In [4]:
X = df.iloc[:, :-1].to_numpy()
Y = df['per capita income (US$)'].to_numpy()

In [6]:
B = np.linalg.inv(X.T @ X) @ X.T @ Y
B


array([-1.63221076e+06,  8.28465075e+02])

In [7]:
y = B[0] + 2020 * B[1]
print("Per Capita Income in 2020: ", y)

Per Capita Income in 2020:  41288.694094381295


In [23]:
df = pd.read_csv('ML Lab 3\\salary.csv')
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)
df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [ ]:
df.insert(0, "bias", 1)
X = df.iloc[:, :-1].to_numpy()
Y = df['Salary'].to_numpy()
B = np.linalg.inv(X.T @ X) @ X.T @ Y
B

array([26265.98773186,  9398.64060184])

In [25]:
y = B[0] + B[1] * 12
print("Salary at 12 years: ", y)

Salary at 12 years:  139049.6749539778


In [51]:
df = pd.read_csv("ML Lab 3/hiring.csv")
df = df.replace({"experience": 
            {
                np.nan: 0,
                "two": 2,
                "three": 3,
                "five": 5,
                "seven": 7,
                "ten": 10,
                "eleven": 11
            }
            })
df["experience"] = df["experience"].astype(int)
df = df.dropna()
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
7          11                    7.0                           8      80000

In [ ]:
df.insert(0, "bias", 1)

In [53]:
X = df.iloc[:, :-1].to_numpy()
Y = df.iloc[:, -1].to_numpy()
B = np.linalg.inv(X.T @ X) @ X.T @ Y
B

array([15862.65779687,  3083.86150542,  2146.66596826,  2081.19008957])

In [55]:
x = np.array([1, 2, 9, 6])
y = B @ x
print("1. ", y)
x = np.array([1, 12, 10, 10])
y = B @ x
print("2. ", y)

1.  53837.51505945294
2.  95147.55644020853


In [70]:
df = pd.read_csv("ML Lab 3/1000_Companies.csv")
state_dummies = pd.get_dummies(df["State"], drop_first=True)
df = pd.concat([df.drop("State", axis=1), state_dummies], axis=1)
df = df.apply(pd.to_numeric)
bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)
df = df[[c for c in df.columns if c != "Profit"] + ["Profit"]]

df.head()

R&D Spend  Administration  Marketing Spend  Florida  New York     Profit
0  165349.20       136897.80        471784.10        0         1  192261.83
1  162597.70       151377.59        443898.53        0         0  191792.06
2  153441.51       101145.55        407934.54        1         0  191050.39
3  144372.41       118671.85        383199.62        0         1  182901.99
4  142107.34        91391.77        366168.42        1         0  166187.94

In [71]:
df.insert(0, "bias", 1)

In [72]:
X = df.iloc[:, :-1].to_numpy()
Y = df.iloc[:, -1].to_numpy()
B = np.linalg.inv(X.T @ X) @ X.T @ Y
B

array([-7.00512495e+04,  5.53149346e-01,  1.02624663e+00,  8.10861610e-02,
       -4.46353536e+02,  9.77276094e+01])

In [73]:
x = np.array([1, 91694.48, 515841.3, 11931.24, 1, 0])
y = B @ x
print("1. ", y)

1.  510570.9926108301
